CREATE TABLE USUARIO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL,
    GENERO VARCHAR NOT NULL,
    PAIS VARCHAR NOT NULL,
    DATANASCIMENTO DATE NOT NULL
);
