CREATE TABLE USUARIO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL,
    OBSERVACOES VARCHAR NOT NULL,
    PAIS VARCHAR NOT NULL,
    GENERO VARCHAR NOT NULL,
    MAIORIDADE BOOLEAN NOT NULL
);

INSERT INTO USUARIO (NOME, EMAIL, OBSERVACOES, PAIS, GENERO, MAIORIDADE) 
VALUES ('CARLOS PEREZ', 'carlitosPerez123@hotmail.com', 'PROFISSIONAL DE FREELANCER', 'ARGENTINA', 'MASCULINO', TRUE);

INSERT INTO USUARIO (NOME, EMAIL, OBSERVACOES, PAIS, GENERO, MAIORIDADE) 
VALUES ('MANOELA MANGA', 'mangaManoela@gmail.com', 'ESTUDANTE DE DIREITO', 'BRASIL', 'FEMININO', TRUE);

INSERT INTO USUARIO (NOME, EMAIL, OBSERVACOES, PAIS, GENERO, MAIORIDADE) 
VALUES ('ENZO HERRERA', 'enzo.herrera@outlook.com', 'MOTORISTA DE APLICATIVO', 'PARAGUAI', 'NÃO INFORMADO', TRUE);

INSERT INTO USUARIO (NOME, EMAIL, OBSERVACOES, PAIS, GENERO, MAIORIDADE) 
VALUES ('RODRIGO CUNHA', 'cunha.digo1@gmail.com', '', 'BRASIL', 'NÃO BINÁRIO', TRUE);

INSERT INTO USUARIO (NOME, EMAIL, OBSERVACOES, PAIS, GENERO, MAIORIDADE) 
VALUES ('CARLOS AGOSTINHO', 'carlos.agostinho5@gmail.com', 'ESTUDANTE DO ENSINO MÉDIO', 'BRASIL', 'MASCULINO', FALSE);
